dashboard_import:
  package_import_url: github://MariuszWoszczynski/Level-sensor/level-sensor.yaml@main
  import_full_config: true
 
substitutions:
  name: level-sensor
  friendly_name: Level sensor
  status_led: GPIO02
  
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: esphome.level_sensor
    version: "1.0"
 
esp32:
  board: nodemcu-32s 
  framework:
    type: arduino


time:
 - platform: sntp
   id: time_sntp
 
 
# Enable logging
logger:
  level: debug
 
# Enable Home Assistant API
api:
  encryption:
    key: "f1OnO1pFrP+WH/bsrxh6dmfoLOSwxx19NN6jGu348pk="

ota:
  - platform: esphome
    password: "ef6ad0390dea3e1631dfeeb4835d57b7"
 
wifi:
  ssid: "Woszu_IoT"
  password: "8181818181"
  output_power: 18dB
#  static IP configuration (instead of data from the secret file)
#  manual_ip:
#    static_ip: 192.168.10.219
#    gateway: 192.168.10.1
#    subnet: 255.255.255.0
 
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Level sensor AP"
#    password: "password_12345678"
 
# Status LED for connection
status_led:
  pin:
    # Blue LED
    number: ${status_led}

captive_portal:
 
web_server: 
  port: 80
  version: 3


sensor:
  - platform: ultrasonic
    trigger_pin: GPIO33
    echo_pin: GPIO25
    name: "Level - [m]"
    id: level_m
    update_interval: 10s
    timeout: 1m
    accuracy_decimals: 2
    filters:
      - median:
          window_size: 5
          send_every: 1
          send_first_at: 1

  - platform: template
    name: "Level [%]"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 10s
    lambda: |-
      if (isnan(id(level_m).state)) {
        return NAN;
      }
      const float empty = 0.70;           // Odległość przy pustym zbiorniku (m)
      const float full  = 0.10;           // Odległość przy pełnym zbiorniku (m)
      float percent = (empty - id(level_m).state) / (empty - full) * 100.0;
      if (percent > 100.0) percent = 100.0;
      if (percent < 0.0) percent = 0.0;
      return roundf(percent);

